apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-kafka-operator
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management 
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-kafka-ns
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace # must have openshift-ptp
                metadata:
                  name: kafka
                #labels:
                #  openshift.io/cluster-monitoring: "true"
                #  name: openshift-ptp
                spec: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-kafka-operatorgroup
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  annotations:
                    olm.providedAPIs: Kafka.v1beta2.kafka.strimzi.io,KafkaBridge.v1beta2.kafka.strimzi.io,KafkaConnect.v1beta2.kafka.strimzi.io,KafkaConnectS2I.v1beta2.kafka.strimzi.io,KafkaConnector.v1beta2.kafka.strimzi.io,KafkaMirrorMaker.v1beta2.kafka.strimzi.io,KafkaMirrorMaker2.v1beta2.kafka.strimzi.io,KafkaRebalance.v1beta2.kafka.strimzi.io,KafkaTopic.v1beta2.kafka.strimzi.io,KafkaUser.v1beta2.kafka.strimzi.io
                  name: kafka-operators
                  namespace: kafka
              spec:
                targetNamespaces:
                  - kafka                
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-kafka-subscription
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: strimzi-kafka-operator
                  namespace: kafka
                spec:
                  channel: strimzi-0.23.x
                  name: strimzi-kafka-operator
                  source: community-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-kafka-operatorconfig
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: kafka.strimzi.io/v1beta2
                kind: Kafka
                metadata:
                  name: kafka-brokers-cluster
                  namespace: kafka
                spec:
                  kafka:
                    replicas: 3
                    version: 2.7.0
                    logging:
                      type: inline
                      loggers:
                        kafka.root.logger.level: "INFO"
                    readinessProbe:
                      initialDelaySeconds: 15
                      timeoutSeconds: 5
                    livenessProbe:
                      initialDelaySeconds: 15
                      timeoutSeconds: 5
                    listeners:
                      - name: plain
                        port: 9092
                        type: internal
                        tls: false
                        configuration:
                          useServiceDnsDomain: true
                      - name: external
                        port: 9093
                        type: route
                        tls: true
                    config:
                      auto.create.topics.enable: "false"
                      offsets.topic.replication.factor: 2
                      transaction.state.log.replication.factor: 3
                      transaction.state.log.min.isr: 2
                      log.message.format.version: 2.7
                      inter.broker.protocol.version: 2.7
                      ssl.cipher.suites: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
                      ssl.enabled.protocols: "TLSv1.2"
                      ssl.protocol: "TLSv1.2"
                    storage:
                      type: ephemeral
                  zookeeper:
                    replicas: 3
                    logging:
                      type: inline
                      loggers:
                        zookeeper.root.logger: "INFO"
                    storage:
                      type: ephemeral
                  entityOperator:
                    topicOperator: {}
                    userOperator: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-kafka-topic-1
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: kafka.strimzi.io/v1beta2
                kind: KafkaTopic
                metadata:
                  name: metrics
                  namespace: kafka
                  labels:
                    strimzi.io/cluster: kafka-brokers-cluster
                spec:
                  partitions: 1
                  replicas: 2
                  config:
                    cleanup.policy: compact               
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-kafka
placementRef:
  name: placement-policy-kafka
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-kafka-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-kafka
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"